### ISSUE TITLE
bios

### ISSUE THREAD

**Issue by whoburg** [aeroa/aeroa.github.io#11]
It would be great if everyone wrote a short paragraph to sit beside their headshot on the People page. If this happens, we can change the current grid layout to a list/table with pictures on the left and text to the right.

Sidenote: this would also be a nice layout for the Projects page, with a graphic set next to a short project description. Anyone have good ideas for the HTML / Jekyll to implement that cleanly?

**Comment by bqpd** [comment]
Jekyll-wise, It should be doable in a similar way to `headshot.html`'s templating.

HTML-wise, just sticking a flexbox or table inside the headshot template should work?
