### ISSUE TITLE
projects page needs thumbnails

### ISSUE THREAD

**Issue by whoburg** [aeroa/aeroa.github.io#18]
graphics and images would make this page much more exciting

**Comment by bqpd** [comment]
Yeah! Will you email people and ask for thumbnails on their projects, or should I include it in my "hey you guys said these are your projects at group meeting, send me links" email?

**Comment by whoburg** [comment]
website todo e-mail sent!

**Comment by 1ozturkbe** [comment]
Added potential thumbnail image for D8 in branch ymlFormat, commit dacb17b. 
It is public/images/d8_windTunnel.jpg.

**Comment by 1ozturkbe** [comment]
All projects that are currently up have thumbnails. I am closing this, will open as more projects pop up.
