### ISSUE TITLE
better storage of people data

### ISSUE THREAD

**Issue by bqpd** [aeroa/aeroa.github.io#20]
perhaps as done in https://github.com/uw-ictd/uw-ictd.github.io

**Comment by 1ozturkbe** [comment]
Hmm. I don't see exactly what is it you don't like about the current structure. Can you please elaborate?

**Comment by whoburg** [comment]
I like the website linked to above though!

**Comment by bqpd** [comment]
They store bios in their people.yml: https://github.com/uw-ictd/uw-ictd.github.io/blob/master/_data/people.yml

**Comment by 1ozturkbe** [comment]
Great. To be honest I don't find that to be an inconvenience, quite the opposite! It is nice that people can edit their bios without having to mess with index.html. It also gives people tons of creativity to make an embedded webpage with images, or create an external website!

We were also having the discussion of whether or not we should have the bios directly in the people page, or have the bios be in links. I personally feel the second is better, but feel free to weigh in. 

PS. All students in uw-ictd have external links to their own websites (a decent few of which return 404s :p) Fun times.

**Comment by whoburg** [comment]
Slight leaning toward bios inline; I think that if the bios are kept concise enough and the layout is good, inline bios will be more likely to be read.

**Comment by bqpd** [comment]
Agree with @whoburg

**Comment by 1ozturkbe** [comment]
Sounds good. Perhaps we should convert to .yml format like uw-ictd; that would keep it super clean. I can look into it later today if you are busy @bqpd.

**Comment by bqpd** [comment]
yeah, not much able to work on the website stuff until the 14th...

**Comment by 1ozturkbe** [comment]
@bqpd you should check out the bio format in the ymlFormat branch when you have time. It looks good, but now the more verbose bios are not looking so great. 

I was thinking that we could perhaps keep the individual markdown files (eg. bozturk_bio.md) within links, and have a shortened blurb within the people section. Let me know what you think. @whoburg please weigh in too.

**Comment by 1ozturkbe** [comment]
A bump on this thread @bqpd. The new bio format has been sitting for a few days under ymlFormat. Let me know what you think. I think now some of the bios are too verbose; we need to figure out exactly what should go in the People page, and what should go into bio pages one more level down.

**Comment by bqpd** [comment]
Ah, sorry for the delay! I probably won't get to this until Tuesday.

**Comment by bqpd** [comment]
Overall it looks great, I just need to install Jekyll and mess about with the formatting.

**Comment by 1ozturkbe** [comment]
@bqpd are we satisfied now?

**Comment by bqpd** [comment]
Yes yes!
