### ISSUE TITLE
title too long?

### ISSUE THREAD

**Issue by bqpd** [aeroa/aeroa.github.io#30]
@1ozturkbe, the title "Prototype of the Jungle Hawk Owl, UAV designed using GPkit, has first flight!" causes a linewrap in the homepage summary on my computer; should it be a bit shorter?

**Comment by 1ozturkbe** [comment]
Perhaps cut out 'Prototype of"?

**Comment by bqpd** [comment]
Works for me! See also the branch where I made some more radical changes.

**Comment by 1ozturkbe** [comment]
darn, that didn't work. Will do another pull request; agree that title looks funny.
