### ISSUE TITLE
Templates breaking argghh. 

### ISSUE THREAD

**Issue by 1ozturkbe** [aeroa/aeroa.github.io#47]
@bqpd I don't know why this is happening, but the template is breaking on all pages other than 'home' and 'projects'. We need to fix this ASAP. I'm doing my best to figure it out, but may need your help.

**Comment by bqpd** [comment]
Without any changes to master? Probably an update to Github's Jekyll version...if you match on your local machine you may be able to reproduce.

**Comment by 1ozturkbe** [comment]
... I can't. Locally, it works fine, but online not :/ And my version of Jekyll is the latest.

**Comment by whoburg** [comment]
agreed, this is a mess and a priority!!

**Comment by 1ozturkbe** [comment]
Thanks @bqpd for digging into this. This seems to have been resolved! Closing.
