### ISSUE TITLE
url change?

### ISSUE THREAD

**Issue by mayork** [aeroa/aeroa.github.io#49]
Can we change the url to be something more aligned with the new group name?

**Comment by 1ozturkbe** [comment]
@bqpd can we update the website with a new url and cover page as soon as possible? Lmk if I can help you in any way.

**Comment by bqpd** [comment]
new website is go at https://convexengineering.github.io/ / https://github.com/convexengineering/convexengineering.github.io

will get convexengineering.mit.edu soon!
