### ISSUE TITLE
Projects page is blank

### ISSUE THREAD

**Issue by bqpd** [aeroa/aeroa.github.io#7]
Also, do we have more than the two projects already there?

**Comment by whoburg** [comment]
yes, we certainly do -- maybe hide the page till this issue is resolved?

**Comment by bqpd** [comment]
That can be done just by moving the `projects.md` file; maybe to `_drafts`?

**Comment by whoburg** [comment]
done, in #10

**Comment by 1ozturkbe** [comment]
Can we close this now? I think we have resolved the blankness issue. Now we can discuss auto-integration of posts into projects in #17.
